### ISSUE TITLE
Нужно подправить ДЗ2 соответственно пункту 1

### ISSUE THREAD

**Issue by Muxamedin** [FoodDreamer/Lesson2.1#2]
Согласно задания1:

"Создать репозиторий для выполнения домашнего задания на github с любым названием (наприер expereance_py) . Создать директорию в репозитории с названием соответствующем 2му уроку (например lesson_2). В директории создать файл для каждого задания из ДЗ
с произвольным именем. (например taks_import.py, task_my_name.py)"

На github в вашем проэкте для сдачи ДЗ
должна быть создана папка для урока 2 и вней вы можете расположить все скрипты по задачам к ДЗ

Пожайлуйста создайте директорию в этом же проэкте и перенесите туда файл - my_first_diali.py
По выполнению - дайте знать что все готово

**Comment by FoodDreamer** [comment]
Исправил, спасибо
